server:
  port: 10035
  forward-headers-strategy: framework
  servlet:
    context-path: /tinkoff/education
spring:
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
  datasource:
    url: jdbc:postgresql://danbel.ru:5432/tinkoff_education
    username: postgres
    password: danbelZzAa6190
security:
  jwt:
    secret: c2Zqa3NkamZranNkbGtqZmtsc2pka2ZqdmJjeHZic2JkZmJzamtkZA==